### ISSUE TITLE
Recommendation: Freeze external dependencies

### ISSUE THREAD

**Issue by cranklin** [theloopkr/loopchain#13]
I recommend freezing these requirements with static version numbers for security & stability.

https://github.com/theloopkr/loopchain/blob/e4ffb035b91b4a127bce03e7111f2b8d1d8e2d1c/requirements.txt#L5

**Comment by jinhoyoo** [comment]
We just fix the version of 3rd parties for crucial version. It’s just module to print colored log. Thank you for your recommendation.

**Comment by cranklin** [comment]
I left a comment on the first unversioned dependency, but there are several in requirements.txt.
pyopenssl, Flask, request, etc..  openssl libraries/wrappers should definitely be frozen.  The other big dependencies can cause bugs/build issues with future releases & non-backward compatible changes.
