### ISSUE TITLE
Does this project still active ?

### ISSUE THREAD

**Issue by meotimdihia** [theloopkr/loopchain#23]
Resource code and everything have last updates from 2-4 month ago.

**Comment by joyyir** [comment]
I couldn't agree more

**Comment by morenoh149** [comment]
A person that knows korean should email them, you know for sure otherwise.

**Comment by Jinhoyoo-theloop** [comment]
Sorry, we're preparing massive commit after cleaning up codes as soon as possible. Please be patient for a while.
