### ISSUE TITLE
약간의 오류

### ISSUE THREAD

**Issue by sarah0070224** [theloopkr/loopchain#3]
안녕하세요..

몇가지 설치 및 안내에 오류가 있는것 같습니다.

1. zip파이을 풀면 디렉토리구조가 도큐먼트와 다릅니다. (loopchain-master 하위에 bin, lib, include등이 생성되야 할거 같은데 현재 디렉토리에 생성됩니다.)

2. 각 Peer상태 확인 하기 새번째는 아래와 같이 수정해야 합니다.
$ curl http://localhost:9100/api/v1/status/peer # 현재 Peer1 의 상태를 보여줍니다.
**-> $ curl http://localhost:9001/api/v1/status/peer # 현재 Peer1 의 상태를 보여줍니다.**

3. 도큐먼트에는 안나와 있지만 블록체인 트렌젝션 height를 확인하는 부분도 9000과 9001로 확인해야 하겠지요.
curl http://localhost:9000/api/v1/blocks
curl http://localhost:9001/api/v1/blocks

**Comment by jinhoyoo** [comment]
안녕하세요, 유진호입니다. 수정사항 요청 감사합니다. 반영토록 하겠습니다.

**Comment by christin3271** [comment]
안녕하세요, 더루프팀입니다. 요청하신 수정 사항에 대한 추가적인 안내를 드리고자 합니다.
 
 1. 현재 Github 상에 있는 loopchain 프로젝트 zip 파일을 푼 후의 디렉토리 구조는 다음과 같습니다.
 ```python
 # ../loopchain-master/loopchain-master
 $ ls
 deploy/            
 include/    
 pip-selfcheck.json  
 radiostation.py*                   
 requirements.txt  
 run_test.sh*  
 setup.sh*
 generate_code.sh*  
 loopchain/  
 proxy_rest_api.md   
 radiostation_proxy_restful_api.md  
 resources/        
 sample_score  
 testcase/
 images/            
 peer.py*    
 pyvenv.cfg          
 README.md                          
 rest_server.py*   
 score/        
 Tutorial.md
 ```
 bin/, lib/는 본 파일에 없으며, include/는 loopchain-master 하위에서 확인하실 수 있습니다. 혹시 다음과 같은 구조로 다운로드 되지 않을 경우, 해당 디렉토리의 목록 구조를 위와 같이 올려주시면 감사하겠습니다.
 
 2, 3. 본 예제는 peer0, peer1, peer2가 각각 9000, 9100, 9200번 PORT를 사용하는 것을 기본으로 만들었습니다. `(sudo) docker ps -a` 명령어를 통해 현재 docker 상에서 돌아가는 container의 목록과 각각의 PORT 번호를 확인하실 수 있습니다.

![inked111111_li](https://user-images.githubusercontent.com/18044644/29609400-10d6523c-8832-11e7-8b6d-d2f1c44dbcfa.jpg)
 
만약에 peer1의 상태 확인에 오류가 발생하였다면, 해당 오류에 대해 자세히 알려주시면 감사하겠습니다.

**Comment by jinhoyoo** [comment]
No more feedback and update, So I'll close it.
